version: "3.4"

x-backend-config: &backend
  image: localizer-backend:latest
  volumes:
    - .:/app
  depends_on:
    - db
  env_file: ${ENV_FILE:-localizer.env}

volumes:
  db_data:

services:
  backend:
    <<: *backend
    container_name: localizer-backend
    restart: always
    ports:
      - "5600:5000"

  migration:
    <<: *backend
    container_name: localizer-migration
    restart: on-failure
    command: flask db upgrade

  db:
    image: mdillon/postgis:11
    container_name: db
    restart: always
    env_file: ${ENV_FILE:-localizer.env}
    ports:
      - "5535:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  