version: 2.1

jobs:
  build-and-deploy:
    # Use the Docker executor to run Docker commands
    docker:
      - image: docker:20.10.12
    # Specify the steps to build and deploy the app
    steps:
      - checkout
      - run:
          name: Pull latest code from master
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd OSMLocalizer && git pull origin master"
      - run:
          name: Build Docker image
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd OSMLocalizer \
            && docker build -t localizer-backend:latest ."
      # SSH into the DigitalOcean droplet and deploy the app using Docker Compose
      - run:
          name: Deploy app
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd OSMLocalizer \
            && docker-compose down \
            && docker-compose up -d"


# Run jobs from above in configurable sequences called workflows
workflows:
  version: 2
  # Workflow name
  build-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master
