version: 2.1

jobs:
  backend-deploy:
    # Use the Docker executor to run Docker commands
    docker:
      - image: docker:20.10.12
    # Specify the steps to build and deploy the app
    steps:
      - checkout
      - run:
          name: Pull latest code from master
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd OSMLocalizer && git pull origin master"
      - run:
          name: Build Docker image
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd OSMLocalizer \
            && docker build -t localizer-backend:latest ."
      # SSH into the DigitalOcean droplet and deploy the app using Docker Compose
      - run:
          name: Deploy backend
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd OSMLocalizer \
            && docker-compose down \
            && docker-compose up -d"
  frontend-deploy:
    docker:
      - image: cimg/node:18.15.0
    steps:
      - checkout
      - run:
          name: Create build
          command: |
            cd frontend \
            && npm install \
            && npm run build
      - run:
          name: Deploy frontend
          command: |
            scp -oStrictHostKeyChecking=no -r frontend/build ${SSH_USER}@${SERVER_IP}:/home/${SSH_USER}/OSMLocalizer/frontend

# Run jobs from above in configurable sequences called workflows
workflows:
  version: 2
  # Workflow name
  build-deploy:
    jobs:
      - backend-deploy:
          filters:
            branches:
              only: master
      - frontend-deploy:
          filters:
            branches:
              only: master
