"""empty message

Revision ID: 07aee6916e78
Revises: ccb41b10996e
Create Date: 2023-01-04 21:36:26.503408

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = "07aee6916e78"
down_revision = "ccb41b10996e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.alter_column(
            "bbox",
            existing_type=Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            nullable=True,
        )
        batch_op.alter_column(
            "centroid",
            existing_type=Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.alter_column(
            "centroid",
            existing_type=Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            nullable=False,
        )
        batch_op.alter_column(
            "bbox",
            existing_type=Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            nullable=False,
        )

    # ### end Alembic commands ###
