"""empty message

Revision ID: 1bfe999ab7ad
Revises: d0820a0ef5a7
Create Date: 2023-03-02 20:22:20.656956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1bfe999ab7ad"
down_revision = "d0820a0ef5a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("feature_instructions", sa.String(length=255), nullable=True)
        )

    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.drop_column("changeset_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("changeset_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.drop_column("feature_instructions")

    # ### end Alembic commands ###
