"""empty message

Revision ID: 34438b4017e4
Revises: 8ba9a722026a
Create Date: 2023-11-17 15:15:41.213906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34438b4017e4'
down_revision = '8ba9a722026a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))
    
    op.execute("UPDATE challenge SET private=False;")
    op.alter_column("challenge", "private", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
