"""empty message

Revision ID: 5adef004fb97
Revises: 62a3d9e9dd1c
Create Date: 2023-02-12 01:25:32.215660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = "5adef004fb97"
down_revision = "62a3d9e9dd1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.add_column(sa.Column("to_language", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("overpass_query", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("translate_engine", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("api_key", sa.String(), nullable=True))
        batch_op.drop_column("feature_tags")

    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.add_column(sa.Column("osm_type", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("osm_id", sa.BigInteger(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "geometry",
                Geometry(
                    geometry_type="POINT",
                    srid=4326,
                    from_text="ST_GeomFromEWKT",
                    name="geometry",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("last_updated", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("changeset_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("localized_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("validated_by", sa.String(), nullable=True))
        batch_op.drop_index("idx_feature_geometry")
        batch_op.create_index(
            "idx_feature_geometry", ["geometry"], unique=False, postgresql_using="gist"
        )
        batch_op.drop_column("element_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("element_type", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_index("idx_feature_geometry", postgresql_using="gist")
        batch_op.drop_column("validated_by")
        batch_op.drop_column("localized_by")
        batch_op.drop_column("changeset_id")
        batch_op.drop_column("last_updated")
        batch_op.drop_column("geometry")
        batch_op.drop_column("osm_id")
        batch_op.drop_column("osm_type")

    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "feature_tags",
                postgresql.ARRAY(sa.VARCHAR()),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("api_key")
        batch_op.drop_column("translate_engine")
        batch_op.drop_column("overpass_query")
        batch_op.drop_column("to_language")

    # ### end Alembic commands ###
