"""empty message

Revision ID: 62a3d9e9dd1c
Revises: 07aee6916e78
Create Date: 2023-01-04 21:38:34.591796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "62a3d9e9dd1c"
down_revision = "07aee6916e78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("feature_tags", postgresql.ARRAY(sa.String()), nullable=False)
        )
        batch_op.drop_column("features_tags")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "features_tags",
                postgresql.ARRAY(sa.VARCHAR()),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("feature_tags")

    # ### end Alembic commands ###
