"""empty message

Revision ID: 74955f887ad0
Revises: 1bfe999ab7ad
Create Date: 2023-03-21 21:59:06.300495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74955f887ad0"
down_revision = "1bfe999ab7ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.add_column(sa.Column("skipped_by", sa.BigInteger(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_feature_skipped_by"), ["skipped_by"], unique=False
        )
        batch_op.create_foreign_key("fk_users_skipped", "users", ["skipped_by"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_skipped", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_feature_skipped_by"))
        batch_op.drop_column("skipped_by")

    # ### end Alembic commands ###
