"""empty message

Revision ID: 9e62b17b0250
Revises: 85b6bea15d67
Create Date: 2023-02-26 19:05:02.585452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e62b17b0250"
down_revision = "85b6bea15d67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key("fk_users", "users", ["created_by"], ["id"])

    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked_by", sa.BigInteger(), nullable=False))
        batch_op.drop_column("localized_by")
        batch_op.drop_column("validated_by")
        batch_op.add_column(sa.Column("localized_by", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("validated_by", sa.BigInteger(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_feature_localized_by"), ["localized_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_feature_locked_by"), ["locked_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_feature_validated_by"), ["validated_by"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_users_localizer", "users", ["localized_by"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_users_validator", "users", ["validated_by"], ["id"]
        )
        batch_op.create_foreign_key("fk_users_locker", "users", ["locked_by"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_locker", type_="foreignkey")
        batch_op.drop_constraint("fk_users_validator", type_="foreignkey")
        batch_op.drop_constraint("fk_users_localizer", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_feature_validated_by"))
        batch_op.drop_index(batch_op.f("ix_feature_locked_by"))
        batch_op.drop_index(batch_op.f("ix_feature_localized_by"))
        batch_op.alter_column(
            "validated_by",
            existing_type=sa.BigInteger(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "localized_by",
            existing_type=sa.BigInteger(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.drop_column("locked_by")

    with op.batch_alter_table("challenge", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users", type_="foreignkey")
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
