"""empty message

Revision ID: bf6dad02be82
Revises: 
Create Date: 2022-12-15 16:37:16.423552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6dad02be82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('corrected', sa.String(), nullable=True),
    sa.Column('google_translate', sa.String(), nullable=True),
    sa.Column('text_ne', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translate_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['translate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translate_history')
    op.drop_table('translate')
    # ### end Alembic commands ###
