"""empty message

Revision ID: d0820a0ef5a7
Revises: 7b247be5e731
Create Date: 2023-03-01 22:47:33.818544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0820a0ef5a7"
down_revision = "7b247be5e731"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.drop_column("osm_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("osm_id", sa.BIGINT(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
