export const MAPBOX_ACCESS_TOKEN = process.env.REACT_APP_MAPBOX_ACCESS_TOKEN;
export const OAUTH_CLIENT_ID = process.env.REACT_APP_OAUTH_CLIENT_ID;
export const OAUTH_CLIENT_SECRET = process.env.REACT_APP_OAUTH_CLIENT_SECRET;
export const DEFAULT_CHANGESET_COMMENT = 
  process.env.REACT_APP_DEFAULT_CHANGESET_COMMENT || "#OSMLocalizer #LocalizeNepal";
